# This is a basic workflow to help you get started with Actions

name: Caller

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    - cron: '10 * * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ref:
    uses: korea-dinos/ajaykn-schedule/.github/workflows/called.yml@main
